### ISSUE TITLE
Feedback Sprint 2

### ISSUE THREAD

**Issue by nerdale** [LoretoGH/scl-2018-05-bc-core-am-datadashboard#5]
Hola chicas!
Estuve revisando el avance que llevan y tengo algunos comentarios:

1. En el archivo **eslintrc** tienen conflictos sin solucionar en las líneas 2, 3 y 5, mucho ojo con esos detalles

2. Recuerden el orden del linkeo de los archivos css en los archivos html, en el **datadashboard.html**, **graficos.html**, **index.html**, **select.html** y **select-cohort.html** lo tienen incorrecto.

3. Utilicen todo el HTML semántico, con eso me refiero a las etiquetas `<header></header> <section></section> <article></article> <aside></aside> <nav></nav> <footer></footer>`

4. Utilicen milestones para ver el avance de los issues, esto es como un trello pero en github (similar) , les dejo dos vídeos de guía https://www.youtube.com/watch?v=9SZSHGA95x4
https://www.youtube.com/watch?v=nI5VdsVl0FM

5. Ojo en el archivo **style.css** tienen un error con el float de la línea 23

6. Recuerden que la indentación es de 2 espacios, están utilizando 4 en el **style.css**

7. Dejen lo más limpio sus archivos, eviten los espacios (enter) innecesarios.

8. Utilicen comentarios a lo largo de su proyecto en los archivos.

9. Usen los issues para coordinarse y comunicarse entre ustedes, hasta el momento no tienen issues ni milestones.

Vamos con todo! :rocket:

**Comment by Carolinadelb** [comment]
Gracias Ale, lo cambiaremos. Suerte con tu viaje. :+1:

**Comment by LoretoGH** [comment]
Vamos a realizar las correcciones necesarias. Gracias :)
